In [3]:
import numpy as np

### Array的属性
---

In [7]:
array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array)
print('number of dim:', array.ndim)    # ndim: dimension
print('shape:', array.shape)    # shape：(行，列)

print('size:', array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


### 创建Array与格式
---

In [16]:
a = np.array([[2, 3, 4],
              [3, 4, 6]], dtype=np.float32)
print(a.dtype)

float32


1. `linespace`可以进行分段，并返回分段节点，前两个参数是首尾节点，最后一个参数是节点数（即段数+1）

In [35]:
zeros_mat = np.zeros((3, 5))
print(zeros)
ones_mat = np.ones((5, 6), dtype=np.float32)
print(ones_mat)
empty_mat = np.empty((3, 4))    # empty生成的是每个元素非常接近零的矩阵
print(empty_mat)
arange_vec = np.arange(12).reshape((3, 4))
print(arange_vec)
linesapce_mat = np.linspace(1, 10, 3)
print(linesapce_mat)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[  1.    5.5  10. ]
